def update_plot(ax_img, ax_loss, sample, l, pred, mlp_digit, prob_pred, losses_D, losses_G, epoch):
    ax_img.clear()
    ax_img.imshow(sample.cpu().numpy().reshape(l, l), cmap='gray')
    ax_img.set_title(f'Predição D: {pred:.3f}\nProb_{mlp_digit}: {prob_pred:.3f}', fontsize=10)
    ax_img.axis('off')
    ax_img.text(0.5, 0.5, mlp_digit, fontsize=40, ha='center', va='center', color='red', transform=ax_img.transAxes)
    ax_loss.clear()
    ax_loss.plot(losses_D, label='D_loss', color='tab:orange', linewidth=1)
    ax_loss.plot(losses_G, label='G_loss', color='deepskyblue', linestyle='dotted', linewidth=2)
    ax_loss.set_title('Losses', fontsize=10)
    ax_loss.set_xlabel('Época', fontsize=8)
    ax_loss.set_ylabel('Loss', fontsize=8)
    ax_loss.legend(fontsize=8, loc='upper left')
    ax_img.figure.suptitle(f'Época {epoch + 1}', fontsize=12)
    import matplotlib.pyplot as plt
    plt.pause(0.01)
